package org.bndtools.demo.webapp;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.servlet.Servlet;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.osgi.service.component.annotations.Activate;
import org.osgi.service.component.annotations.Component;
import org.osgi.service.servlet.whiteboard.propertytypes.HttpWhiteboardServletPattern;

@Component
@HttpWhiteboardServletPattern("/example/*")
public class ExampleServlet extends HttpServlet implements Servlet {

	private static final long serialVersionUID = 1L;
	
	@Activate
	public ExampleServlet() {
		System.out.println("Go to URL in your browser: http://localhost:8080/example");
	}

	public void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO: method generated by template
		response.setContentType("text/html");
		response.getWriter().write("Hello world at " + new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS").format(new Date()));
	}

}